### PR TITLE
[OMEGA-154] List dependencies needed to build janus-swi library

### PR DESCRIPTION
**Pull request by vsbogd**
## Description
While looking at https://github.com/asi-alliance/OmegaClaw-Core/issues/172 I have found that list of dependencies in README.md is not full.

## How Has This Been Tested?
Run empty docker container using Ubuntu 26.04 image:
```sh
docker run --rm -ti ubuntu:26.04
```
Follow the installation guide: https://github.com/asi-alliance/OmegaClaw-Core/tree/add-dependencies-into-readme#installation

## Checklist
- [x] The code generated by LLM is reviewed by the PR creator
- [x] Self-review completed
- [x] Test scenarios above are passed with the version of the code from PR

### CODE REVIEW

**Review by blackhammer116 — APPROVED** [review]

File: README.md [hunk 1]
```diff
@@ -54,7 +59,7 @@ source ./.venv/bin/activate
 
 If you have CPU only machine or don't want calculate embeddings on GPU:
 ```
-python3 -m pip install --index-url https://download.pytorch.org/whl/cpu torch
+python3 -m pip install --index-url https://download.pytorch.org/whl/cpu torch==2.5.1
```
Comment (vsbogd) [inline README.md]: I have found that for Python 3.14 there is no 2.5.1 version so I will wipe the explicit version from here:
```suggestion
python3 -m pip install --index-url https://download.pytorch.org/whl/cpu torch
```

**Comment by TossSky** [comment]
@vsbogd 
Tested OMEGA-154 on a clean `ubuntu:26.04` container.

What I checked:
- [x] The README `apt-get` command is valid: all six packages resolve and install on 26.04.
- [x] `pip install janus-swi==1.5.2` fails to build on 26.04 with both the old and the new prerequisite list.
- [x] On a default `apt-get` the two added packages come in anyway: `python3-pip` 
Recommends `python3-dev` and `build-essential`, so without `--no-install-recommends` the old and new lists install the same set.

The build failure is identical in both cases and isn't about the dependency list:

```
janus/janus.c:2631: error: passing argument 4 of 'PL_register_foreign_in_module' from incompatible pointer type [-Wincompatible-pointer-types]
ERROR: Failed building wheel for janus-swi
```

`gcc-15` on 26.04 promotes `-Wincompatible-pointer-types` to an error, and `janus-swi 1.5.2` doesn't compile against the SWI-Prolog 9.2.9 headers. So running the guide through to `pip install -r requirements.txt` on 26.04 doesn't give a working janus-swi, with or without this change.

The README command is fine on its own. The open items are separate from it: on a default install the new packages don't change what's installed, and the janus-swi build on 26.04 needs a fix beyond the prerequisite list.

**Comment by vsbogd** [comment]
1. It seems the difference is a SWI Prolog version. I used latest stable from SWI Prolog PPA repo which is 10.0.2. And I even suspect you don't need to install janus-swi using this version of swipl (didn't check it yet). May be we need to make 10.0.2 the minimal SWI Prolog version required. @patham9 do you have any objections?

2. I don't like `python3 -m pip install -r ./repos/OmegaClaw-Core/requirements.txt` fails to install `torch==2.5.1` because `python3 -m pip install --index-url https://download.pytorch.org/whl/cpu torch` installs `2.12.0+cpu` and cannot install `2.5.1` probably because Python version on Ubuntu 26.04 is too new. Thus I think we need to upgrade torch version as well.

**Review by jazzbox35 — COMMENTED** [review]
I did my own build from this PR and it worked using my Telegram channel. Approved

Screenshot from 2026-06-26 16-40-55

**Comment by MorozovMisha** [comment]
@vsbogd  Verified on Ubuntu 26.04: janus-swi==1.5.2 builds successfully with SWI-Prolog 10.0.2. README is correct.
